### ISSUE TITLE
Structures do not spawn with TerraForged

### ISSUE THREAD

**Issue by ghost** [stal111/Valhelsia-Structures#100]
Even though its an option to customize the variety in the world gen config of TerraForged they wont spawn. 
Is there any way to make them spawn? 
Already searched trough the issues of the TerraForged hub but havent found an solution. 
Do you consider to support the TerraForged mod? 
Sorry for waisting your time. <3

**Comment by stal111** [comment]
Did you try using /locate to see if the structures are generating? If they are generating you could try to decrease their spacing and separation values in the Valhelsia Structures config file.

**Comment by ghost** [comment]
I tried that and they dont spawn, there are quite a few mods that add
structures to the game that wont spawn with TerraForged. Thats not the
problem.

Am Mo., 27. Sept. 2021 um 20:54 Uhr schrieb stal111 <
***@***.***>:

**Comment by Khytwel** [comment]
Please send an export of your modpack to test this. I personally tried the latest version of Valhelsia Structures with Terraforged and it works perfectly (also with some structure mods).
