### ISSUE TITLE
[crash] mana-and-artifice ritual tries to locate valhelsia:desert_house

### ISSUE THREAD

**Issue by Petrisis** [stal111/Valhelsia-Structures#102]
**Describe the bug**
My Server got killed by watchdog while a player started ritual of locating. its in a crash loop as long as this chunk is loaded.
Server console output: "Failed to parse UUID for ritual caster. Giving up and completing the ritual anyway, but some effects may not apply! "

**To Reproduce**
1. play with mana&artifice and valhelsia structures (or just valhelsia + /locate) inside the modpack [Crashed on Gyrnolia](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia)
2. generate a world with quark_realistic setting
3. locate with m&a (or /locate) a "valhesia:desert_house"
4. start the ritual and the server will be shut down by a ticks taking to long

**Expected behavior**
The ritual/command should just work as its defined and not crash.

**Version Information:**
* Mod Version: 0.1.5
* Valhelsia Core: 16.0.0
* Modpack Version: [0.7.5](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia/files/3454548)
* Forge Version 36.2.2

**Additional context**
i'm concerned that this could be a forge/valhelsia problem with some structure generation not working properly or /locate command doing stuff.

[server crash report](https://gist.github.com/Petrisis/61fca017b4d36256043b8d779255ede5)

**Comment by stal111** [comment]
Does this still happen with Valhelsia Structures 0.1.6? My guess is that this should have been fixed.
