### ISSUE TITLE
[Valhelsia Core] Internal verification (no relation to Valhelsia Structures).

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Valhelsia-Structures#103]
While I was updating and testing my pack, [Create in Chaos](https://www.curseforge.com/minecraft/modpacks/create-in-chaos) I keep seeing the error as shown in the attached text file. Neither the client or server crash, but it keeps adding about 40+ lines of errors I would like fixed. 

Minecraft 1.16.5
Forge to 36.2.6
valhelsia_core-16.0.11

Thank you!
CM

[console-log.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7270545/console-log.txt)

**Comment by Khytwel** [comment]
Hey, it's not too bad, this error happens when a player logs in/out. This will be fixed in the next update of our API. In any case, it does not cause lag, etc...

**Comment by ClaudiusMinimus** [comment]
Thank you!

**Comment by Khytwel** [comment]
Hey, this should be fixed with the latest version of Valhelsia Core: https://www.curseforge.com/minecraft/mc-mods/valhelsia-core/files/3490931
