### ISSUE TITLE
[1.16.5] NullPointer crash when used in void/skylands world

### ISSUE THREAD

**Issue by PG85** [stal111/Valhelsia-Structures#113]
When using Valhelsia-structures with OTG-1.16.5 for normal overworld-like worlds, everything is lovely:

![2021-11-25_18 43 28](https://user-images.githubusercontent.com/6781444/143485624-adabc3cd-55e0-4e12-884d-5f4e0bcf7478.png)
* OTG Wildlands preset, lovely.

When using Valhelsia-structures with OTG-1.16.5 and the Skylands preset, which like the End is a floating islands world, sooner or later I get a nullpointerexception and a crash. I assume this may be due to void worlds not being taken into account?

Log: https://gist.github.com/PG85/8a4db92e0287551326027df10bd4915f
OTG 1.16: https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator/files/3535174
Skylands: https://www.curseforge.com/minecraft/mc-mods/otg-skylands/files

Thanks!

**Comment by stal111** [comment]
Haven't had the time yet to look closely on how OTG's chunk generator works but could it maybe be that you return null in the getBaseHeight or getBaseColumn method? Because the crash happens due to one of them being null which should normally not happen from what i know.

**Comment by PG85** [comment]
Thanks for looking at this, I see I was using a different version so the line numbers didn't match up. Ended up going down the rabbit hole and finding an obscure bug, crash should be fixed for OTG 1.16.5 0.1.6.

Had to tweak some settings, but got things to work in skylands:
![2021-11-28_20 18 20](https://user-images.githubusercontent.com/6781444/143782716-87e20b5f-b579-4788-be1c-2b3e5f6ef841.png)
: 

Thanks!
