### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by xz123456xz** [stal111/Valhelsia-Structures#115]
> 	[structures.spawner_dungeon]
> 		#Generate? [default: true]
> 		generate = true
> 		#Spawn Chance [default: 0.7]
> 		#Range: 0.0 ~ 1.0
> 		spawn_chance = 0.7
> 		#Spacing (in chunks) [default: 30]
> 		#Range: 0 ~ 200
> 		spacing = 30
> 		#Minimum Separation (in chunks) [default: 8]
> 		#Range: 0 ~ 200
> 		separation = 8
> 		#Biome Categories the structure can generate in 
> 		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether, underground]
> 		biome_categories = ["plains", "forest", "extreme_hills", "taiga", "desert", "mesa", "savanna", "jungle", "icy", "swamp", "mushroom"]
> 		#Dimensions the structure can NOT generate in
> 		blacklisted_dimensions = ["twilight_forest"]
> 		#Biomes the structure can NOT generate in
> 		blacklisted_biomes = []

Hope that Twilight Forest prohibits the generation of structures. Such a setting does not work.
Want to ban spawning in Twilight , because he will spawn in the air

![unknown](https://user-images.githubusercontent.com/52368359/144193744-b0abba78-5c54-4d4b-8935-91573cfa210a.png)

**Comment by Vaelzan** [comment]
You need to use "twilightforest", not "twilight_forest". There's no underscore in the dimension ID.

**Comment by xz123456xz** [comment]
ok~
