### ISSUE TITLE
No way to configure dimensions

### ISSUE THREAD

**Issue by xz123456xz** [stal111/Valhelsia-Structures#116]
> 	[structures.spawner_dungeon]
> 		#Generate? [default: true]
> 		generate = true
> 		#Spawn Chance [default: 0.7]
> 		#Range: 0.0 ~ 1.0
> 		spawn_chance = 0.7
> 		#Spacing (in chunks) [default: 30]
> 		#Range: 0 ~ 200
> 		spacing = 30
> 		#Minimum Separation (in chunks) [default: 8]
> 		#Range: 0 ~ 200
> 		separation = 8
> 		#Biome Categories the structure can generate in 
> 		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether, underground]
> 		biome_categories = ["plains", "forest", "extreme_hills", "taiga", "desert", "mesa", "savanna", "jungle", "icy", "swamp", "mushroom"]
> 		#Dimensions the structure can NOT generate in
> 		blacklisted_dimensions = [twilightforest]
> 		#Biomes the structure can NOT generate in
> 		blacklisted_biomes = []

According to the configuration you said, the game won't open.
The game crashed whilst rendering overlay.

collapse:https://gist.github.com/xz123456xz/974c43ed7212517455910bb2a8791a44

**Comment by Vaelzan** [comment]
Now you're missing the double quotes. You only needed to remove the underscore.

Please use the Discord server if you need further support instead of opening further issues here.

**Comment by xz123456xz** [comment]
Add double quotes.
It will be cleared when you start the game.
