### ISSUE TITLE
Exit Code 0 with latest 1.18 version

### ISSUE THREAD

**Issue by xandertreat** [stal111/Valhelsia-Structures#117]

**Comment by stal111** [comment]
Some more information would be good. My first assumption would be that you're missing Valhelsia Core which is a required dependency. Do you have that mod installed?

**Comment by xandertreat** [comment]
> Some more information would be good. My first assumption would be that you're missing Valhelsia Core which is a required dependency. Do you have that mod installed?

No.. Sorry. I wish that was stated on the page.
