### ISSUE TITLE
[1.18.1] Crash when using Forge >= 39.0.45.

### ISSUE THREAD

**Issue by Shacklefty** [stal111/Valhelsia-Structures#119]
The server starts up and I can load into the world, but as soon as I begin to move around and load new chunks, it crashes.

Appears to be due to Valhelsia Structures, though I'm not savvy enough to understand what specifically.

Here's a crash report. I can provide more if need be, the crash report is the same every time.
https://pastebin.com/Yv6r6HsR

Edit:
Versions used-
valhelsia_core-1.18.1-0.3.2.jar
valhelsia_structures-1.18.1-0.1.0.jar

**Comment by HalestormXV** [comment]
Running into a similar issue on Singleplayer as well. 
https://pastebin.com/HB2KGqhW
Forge 39.0.45
valhelsia_core-1.18.1-0.3.2.jar
valhelsia_structures-1.18.1-0.1.0.jar

**Comment by javijmgdev** [comment]
> Running into a similar issue on Singleplayer as well. https://pastebin.com/HB2KGqhW Forge 39.0.45 valhelsia_core-1.18.1-0.3.2.jar valhelsia_structures-1.18.1-0.1.0.jar

I have the same problem:
https://pastebin.com/4DcQm88Q

**Comment by Vexikuri** [comment]
Crashed twice in the past 15 minutes, crash log showing Valhelsia_structures
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)

**Comment by Shacklefty** [comment]
@Vexikuri They posted a workaround on their discord, it's a problem caused by a recent forge update. I downgraded to Forge 39.0.43 and haven't had any issues since.

**Comment by HalestormXV** [comment]
@Shacklefty Unfortunate. I read the Forge changelog and suspected as much when I saw the 39.0.45 changes but wasn't sure. Suppose a wait for an update is in order then. Thanks for letting us know and for providing the forge version in which this issue does not occur. Much appreciated.

**Comment by Vexikuri** [comment]
Yeah, my server is set at 39.0.53 and it's on a looping crash.

**Comment by Klouver-github** [comment]
I also am having the same issue, now I can't go get a doggo :( or live in one of the houses this mod provides

**Comment by Vexikuri** [comment]
It's the newer version of Forge conflicting with mods.  If I remove Valhelsia_structures I no longer get errors.  Now I can boot up the server, but if I use a mod like ore excavation, it crashes the server.

**Comment by javijmgdev** [comment]
I tried to remove a file called JarBlockEntity from the jar file as that seems to be causing the problem, but when the game is loading I get a warning saying that the file is missing. So I don't know what else to do.

**Comment by HalestormXV** [comment]
Forge Changelogs
 - 39.0.45 Remove references to the **now-broken `BlockEntity#save(CompoundTag)`** method (#8235)
 - 39.0.44 update McModLauncher libraries to newer versions

There were a hand-full of mods that I personally were using that made references to this and broke if you updated to the 39.0.45 version of Forge (be it JarBlockEntity, or whatever, doesn't matter). Ultimately you have to wait for the Mod author to do an update or you can use an older version of Forge or remove the Mod. The decision is yours to make. You won't be able to remove a class file from the .jar though. That doesn't do anything except break stuff. Just as an FYI/PSA.

**Comment by Vaelzan** [comment]
@HalestormXV is correct here, their advice should be followed for now - either use Forge 39.0.44 (or earlier) or avoid using the mod for now.

This will be fixed in the next Valhelsia Structures update. I can't give a firm release date for the update since I'm not the one currently developing the mod, it will depend on when Stal has free time.

**Comment by Lesley-Black-Velvet** [comment]
I also have the same issue and probably reported it in another thread.

**Comment by Khytwel** [comment]
Thanks for your report, fixed in the latest version [0.1.1](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files/3625421).
