### ISSUE TITLE
Game crashes when chunks are loaded in singlepayer

### ISSUE THREAD

**Issue by javijmgdev** [stal111/Valhelsia-Structures#120]
Crash code:
https://pastebin.com/4DcQm88Q

**Comment by SigynLaufeyson** [comment]
I'm getting the exact same error.  I even started a new world & the game crashes before the new world finishes loading with the error: 

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

**Comment by msameer** [comment]
Same here

**Comment by emanuele246gi** [comment]
Same to me

**Comment by Campbell314** [comment]
I was getting the same error. Reverted Valhelsia Core mod to the valhelsia_core-1.18.1-0.3.1.jar version (vs valhelsia_core-1.18.1-0.3.2.jar), and the error isn't happening anymore.

**Comment by Vaelzan** [comment]
Closing this issue, duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

For now, please either downgrade to Forge 39.0.44 or earlier, or wait for the next update.
