### ISSUE TITLE
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag 

### ISSUE THREAD

**Issue by ModernGamingWorld** [stal111/Valhelsia-Structures#122]
valhelsia_structures is crashing on the New version of 1.18.1 forge, This same crash happen to chance cubes as well, so I figured I'd post here to let you know your mod is now crashing cause of the same error
[crash-2022-01-21_17.40.43-server.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7917158/crash-2022-01-21_17.40.43-server.txt)
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7917159/latest.log)

**Comment by Vaelzan** [comment]
Closing this issue, duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

For now, please either downgrade to Forge 39.0.44 or earlier, or wait for the next update.
