### ISSUE TITLE
[1.18.1] Dungeon door hit boxes

### ISSUE THREAD

**Issue by zee738** [stal111/Valhelsia-Structures#125]
The Dungeon door's hitboxes are all out of wack for me.
![image](https://user-images.githubusercontent.com/77257130/150666842-409e6d3d-308d-4ce4-826b-5121a52b3a98.png)
![image](https://user-images.githubusercontent.com/77257130/150666929-8463b240-5e61-40c2-af52-5544f5975134.png)

**Comment by Khytwel** [comment]
Thanks for your report, fixed in the latest version [0.1.1](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files/3625421).
