### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by Si1verBeard** [stal111/Valhelsia-Structures#13]
Hi. Wasn't sure how else to contact you.
Tried running this with Forge only to realise the mod is out of date. Any progress on update?
Thank you.

**Comment by Balthizar01** [comment]
The modpack is compatible with forge version 31.2.21 as well as OptiFine 1.15.2 G1 pre27.

If you run the modpack through the Twitch client you should have no problem running it.

You can view information on it in the #changelog channel of our Discord.

**Comment by Vaelzan** [comment]
I'm not sure what you mean. The mod was recently updated. It has been tested with the latest releases of Forge.

**Comment by Si1verBeard** [comment]
Ah, OK. The file I downloaded was an older one (1.12)...yeah. Sorry about that.

**Comment by Si1verBeard** [comment]
Hi,

Thank you for reading and replying to my email.

 

I was clicking on the link labelled 1.15.2 however it was downloading 1.12 version. I have since managed to DL the mod from a pack containing 15 different mods with the 1.15.2 version included.

 

I’m sorry to have bothered you with such a mundane subject. 

If I had spent just a little more time looking about I would have solved this issue myself.

My bad ;(

 

 

Kindest Regards,

 



Raymond Robarts

 

________________________________________________________________________________________________________

 

This E-Mail was posted directly from:  <mailto:strabor@aapt.net.au> strabor@aapt.net.au with/without attachments.

This E-mail (with attachments where applicable) was successfully scanned by Trend Micro Internet Security™ 

Trend Micro™ – your best defence should always be the BEST!

________________________________________________________________________________________________________

 

 

Electronic transmission (E-mail) are not secure and may not be authentic. E-mail cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. If you have any doubts as to the authenticity of the contents, please telephone to confirm. 

This electronic transmission including any attachments is intended only for those to whom it is addressed.

This E-mail may contain information which is copyright, confidential, legally privileged, or exempt from disclosure by law and is intended only for the use of the intended recipient(s). Any claim to privilege is not waived or lost by reason of mistaken transmission of this information.

If you are not the intended recipient, you must not distribute or copy this transmission either in part or whole. Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. If you are not the intended recipient, you should notify the sender. Your cost for doing so may be reimbursed by the sender. 

The original sender does not accept liability for errors or omissions in connection to this E-mail and denies any responsibility for any damage arising from computer virus, data corruption, delay, interruption, unauthorized access or unauthorized amendment.

 

Any opinions or statements contained in this electronic transmission including any attachments are solely those of the author and do not necessarily represent views held by the sender.

 

“Liability limited by a scheme approved under professional standards legislation”
