### ISSUE TITLE
Crashing on start with v 1.1 java 1.18 forge 39.0.66

### ISSUE THREAD

**Issue by bubblesofdeath** [stal111/Valhelsia-Structures#136]
Tried launching with a few other mods but valhelsia is the only mod that crashes the game after trying to launch it

I am on the most recent mod version

Minecraft version is 1.18.1

The Forge version is 39.0.66

all on version 1.18 other mods installed are:
biomes plenty
create
flywheel
infinite music
jei
optifine
terrablender
velhelsia
xaeros world map
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/8147634/latest.log)

**Comment by Vaelzan** [comment]
You're missing Valhelsia Core, one of the dependencies of Valhelsia Structures.
