### ISSUE TITLE
Structure Spawn and texture issue 

### ISSUE THREAD

**Issue by DamienBrittan** [stal111/Valhelsia-Structures#14]
Structures spawn too frequently , even through i change config to 
               [structures.castle_ruin]
		#Generate Castle Ruins?
		generate = true
		#Castle Ruin Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.1
		#Castle Ruin Distance (in chunks) [default: 35]
		#Range: 1 ~ 500
		distance = 500
		#Castle Ruin Minimum Separation (in chunks) [default: 8]
		#Range: 1 ~ 500
		separation = 100
in all structures 

![2020-06-30_10 06 26](https://user-images.githubusercontent.com/60503638/86095007-f5932a00-bab9-11ea-85d1-fdb12a710185.png)

Texture issue . 
![2020-06-30_10 27 39](https://user-images.githubusercontent.com/60503638/86096769-62a7bf00-babc-11ea-9771-0f062592ea2c.png)

**Comment by Vaelzan** [comment]
The texture issue is a thing we'll fix for the next update. It only seems to happen with OptiFine installed but I know the cause anyway- the artist didn't make the texture files a power of two in size.

Structures being close together is something that is on our list. Are they spawning frequently, or just near too each other when they do spawn?

Also, were those settings made before the world was created and does it occur in a new world? I'm trying to gather as much data as I can. I believe you can go lower than 0.1 as well, such as 0.001.

**Comment by Vaelzan** [comment]
I also believe TerraForged terrain generation needs a much lower chance in general due to the terrain being flatter (more potential spawn candidates than normal generation). Try changing the flatness delta (make it more strict) and you might get an improvement.

**Comment by DamienBrittan** [comment]
World was created after i changed config . They spawn both frequently and close to each other .

**Comment by DamienBrittan** [comment]
![2020-06-30_15 59 59](https://user-images.githubusercontent.com/60503638/86129062-d234a300-baea-11ea-84a9-f837ff3b59d1.png)
And , i forgot to mention about structures spawn on top of flowers .
