### ISSUE TITLE
[Bug]: Forge 1.18.2 crash

### ISSUE THREAD

**Issue by Zano1999** [stal111/Valhelsia-Structures#145]
### Describe the issue

The game crash on startup.

### Minecraft Version

1.18.2 (Default)

### Mods Version

- Forge: 40.0.13
- Valhelsia Structures: 1.18.2-0.1.0
- Valhelsia Core: 1.18.2-0.3.0

### Log

```shell
Log file: https://gist.github.com/Zano1999/8073d2562d4159c81d2a022f556db7db

Crash report: https://gist.github.com/Zano1999/4437b475355f6937486034fcc1c3a422
```

**Comment by urmet** [comment]
update your forge. mod is built against forge 40.0.19 but you have 40.0.13

**Comment by Zano1999** [comment]
Thanks, now it works
