### ISSUE TITLE
1.16.1 Structures are extremely rare

### ISSUE THREAD

**Issue by Vanblam** [stal111/Valhelsia-Structures#15]
I love the structures you have in this mod... When I can find them lol. I ran just this mod, voxel map and travelers boots so I could do a valid fly around. I flew around for an hour and through probably 70+ biomes and only found 3 structures ( This is after I set the spawn chance to 1.0). Are they meant to be this rare to find? I've used your mod on 1.15.2 and I ran into your structures all the time on default settings.

**Comment by winnetrie83** [comment]
I can't find any structures lol.

**Comment by aridhol** [comment]
I believe this is related to the Waystones issue perhaps? Some kind of conflict, do you have Waystones @Vanblam ?

**Comment by Starz1222** [comment]
@aridhol I have waystones installed and am facing the same issues. Might there be a fix to get them to work nicely together?

**Comment by Khytwel** [comment]
Fixed in the last update for version 1.16.1.
