### ISSUE TITLE
[Bug]: Valhelsia Core crash with Optifine HD U7

### ISSUE THREAD

**Issue by Catomax262** [stal111/Valhelsia-Structures#157]
### Describe the issue

It crashes when i start the game.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 40.0.20
- Valhelsia Structures: 0.1.0
- Valhelsia Core: 0.4.0

### Log

```shell
https://gist.github.com/Catomax262/19d11d1081888f429f38447ab01448ce
```

**Comment by Vaelzan** [comment]
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147 - OptiFine removes code that Valhelsia Core relies on to work.

**Comment by Catomax262** [comment]
What can i do?
