### ISSUE TITLE
[Bug]: Game cant start 

### ISSUE THREAD

**Issue by pewblaze** [stal111/Valhelsia-Structures#163]
### Describe the issue

Game crashes (Client and Server) on startup. Without the valhelsia mods it works fine.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.0
- Valhelsia Structures: valhelsia_structures-forge-1.19.2-1.0.2
- Valhelsia Core: valhelsia_core-forge-1.19.2-0.5.0

### Log

```shell
https://gist.github.com/pewblaze/192121d53a86dbcd47c1a29628db4568
```

**Comment by Vaelzan** [comment]
The version of Valhelsia Structures that you have is for Forge 43.2.6+, you'll either need to update Forge or switch to Valhelsia Structures 1.0.1 instead of 1.0.2.

**Comment by pewblaze** [comment]
Ah i see, thank you! :)
