### ISSUE TITLE
[Bug]: Forge 44.1.12+ (Minecraft 1.19.3) isn't compatible with Valhelsia Structures.

### ISSUE THREAD

**Issue by BoldAdam21** [stal111/Valhelsia-Structures#166]
### Describe the issue

As soon as I added the Valhelsia Structures mod to my Java mod folder, I opened the launcher, then opened Minecraft Java and it crashed. It gave the error code 1. As soon as I take off the mod it works perfectly fine. It is in the right version. I have deleted and reinstalled it but it still doesn't work.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 1.19.3-forge-44.1.21
- Valhelsia Structures: 1.19.3-1.0.0
- Valhelsia Core: 1.19.3-0.5.1

### Log

```shell
An unexpected issue occurred and the game has crashed. we're sorry for the inconvenience. Exit Code: 1
```

**Comment by Vaelzan** [comment]
Switch to Forge 44.1.10 for now - Forge made a breaking change in some code and we haven't had a chance to update the 1.19.3 version of Valhelsia Structures to suit.

**Comment by Khytwel** [comment]
Fixed with the latest version: https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files/4462698
