### ISSUE TITLE
[MC 1.16.1] Conflict with waystones

### ISSUE THREAD

**Issue by winnetrie83** [stal111/Valhelsia-Structures#17]
This mod is in conflict with waystones mod. 
For some reason it prevents waystones to be generated.
I tested this with waystones chance set to 1 (in each chunk) and none generates, but with valhelsia structures mod taken out
it starts working and in every chunk is a waystone

**Comment by aridhol** [comment]
I'd like to toss this in here, Waystones recently updated and fixed the problem, as far as they were concerned... but maybe not?

Now, Waystones spawn but Valhelsia structures do not spawn at all! See the linked issue for Waystones, above, for contacting that mod's author.

**Comment by nepphhh** [comment]
I have no problems using both.

**Comment by Khytwel** [comment]
As far as I'm concerned, everything works perfectly, whether it's version 1.16.1 or 1.16.3.

**Comment by Vaelzan** [comment]
I'm closing this now since both Waystones and Valhelsia Structures spawn when using the latest versions of both. :)
