### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by m0thknight** [stal111/Valhelsia-Structures#171]
### Describe the issue

Game crash on start.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.8
- Valhelsia Structures: 1.0.2
- Valhelsia Core: 0.5.0

### Log

```shell
https://gist.github.com/m0thknight/fdb6536ec4d49207d5910c024756ce81
```

**Comment by urmet** [comment]
Remove optifine. there was a note about optifine not being supported on the new issue page and it's also a pinned issue.
Duplicate of #147, not going to be fixed
