### ISSUE TITLE
[Bug]: Crash on start with Rubidium+Oculus

### ISSUE THREAD

**Issue by c2oh25n3o** [stal111/Valhelsia-Structures#172]
### Describe the issue

The game just crashes on start due to unknown issue (code 1) when I have Valhelsia Core, Structures and Furniture installed + Rubudium and Oculus. All of these are the latest available versions. There aren't any other mods. 

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.4
- Valhelsia Structures: 1.0.2
- Valhelsia Core: 0.5.0

### Log

```shell
https://gist.github.com/c2oh25n3o/8a0b246940530d767ad82d7d7a5f254c
```

**Comment by Vaelzan** [comment]
Valhelsia Structures 1.0.2 requires Forge 43.2.6 or newer.

If you can't update Forge, use Valhelsia Structures 1.0.1 instead.
