### ISSUE TITLE
[Bug]: Crash on launch

### ISSUE THREAD

**Issue by lab3** [stal111/Valhelsia-Structures#177]
### Describe the issue

We have a bug report in Iron's Spells N Spellbooks but it looks related to your mod.  When launching minecraft the game crashes.  Exception in attached gist.  Let us know if we can help.

https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/22

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: forge:1.19.2-43.2.3
- Valhelsia Structures: valhelsia_structures-forge-1.19.2-1.0.2.jar
- Valhelsia Core: valhelsia_core-forge-1.19.2-0.5.0.jar

Iron's Spells N Spellbooks v1.0.6
- https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/download/4520755

### Log

Exception the kills the game: https://gist.github.com/lab3/74fbdd3b384edc7b548eaa3b3cf86f10
Debug and Latest log: https://gist.github.com/lab3/ed7fcfc50bf15921e8e3d3fe6694c969

**Comment by urmet** [comment]
update forge or downgrade valhelsia structures to 1.0.1. 1.0.2 of structures needs forge 43.2.6 or newer

**Comment by Vaelzan** [comment]
As urmet said, this is just a mismatch between mod + Forge version. Forge made a breaking change wiht 43.2.6 (changing bucket-related code), so we had to update the mod to suit.

**Comment by lab3** [comment]
This makes sense.  Appreciate the quick response.
