### ISSUE TITLE
Colonist Pathing issues

### ISSUE THREAD

**Issue by catrina339** [stal111/Valhelsia-Structures#18]
I am having an issue with colonists not going into the tavern for sleep and instead congregating on the outer corner of the tavern. This is the medieval oak tavern scheme. I did not have this issue with the level one tavern but have had this issue with the level two and three. 
![2020-07-18_21 34 19](https://user-images.githubusercontent.com/68488601/87865898-33a89e80-c940-11ea-85ae-48ac2626e093.png)

**Comment by LittleCircles** [comment]
Im not saying im right, but that looks like MineColonies. Not Valhelsia Structures?

**Comment by catrina339** [comment]
my first time here. Wasnt quite sure where to put this. Was told to put any bugs i had with the mod pack on the git hub here.

**Comment by LittleCircles** [comment]
Ping me on the Valhelsia Discord, we will get you sorted for the correct modpack github =) 

Discord: LittleCircles#9856

**Comment by catrina339** [comment]
I managed to find the mine colonies GitHub via google. I have reported the issue there.
