### ISSUE TITLE
[Bug]: Crash on Launch

### ISSUE THREAD

**Issue by Stormhaven13** [stal111/Valhelsia-Structures#181]
### Describe the issue

...Been testing to see which mod causes my mod set to crash, and weirdly it's Valhelsia Structures. It crashes on launch, giving me Exit Code 1. I tested both in my mod set and with only Valhelsia Core and Structures, no change. Could be something on my end, but if it is it's not something obvious. I'm currently using the Curseforge Launcher

### Minecraft Version

1.18.2

### Mods Version

- Forge: 40.2.9
- Valhelsia Structures: 0.1.0
- Valhelsia Core: 0.4.0

### Log

```shell
https://gist.github.com/Stormhaven13/a09b9448d5d80e4a64c98374b2f323e7
```

**Comment by Kaktus56** [comment]
Install Forge version 40.2.0, it will help.

**Comment by Hojosa** [comment]
To be more precise, the breaking change is Forge 40.2.6. Version 40.2.5 or lower will start without issues

**Comment by JustRed23** [comment]
[This forge patch](https://github.com/MinecraftForge/MinecraftForge/commit/424f43868f5e71c0025d0f6157a5a84097430e4a) breaks the valhelsia_placeDousedTorch mixin

**Comment by stonemandave** [comment]
Any chance this will get updated for newer forge versions. I like this mod but not using forge 40.2.9 or higher breaks other mods.
