### ISSUE TITLE
[Bug]: Valhelsia Structures crashes game on startup

### ISSUE THREAD

**Issue by senselessenvelope** [stal111/Valhelsia-Structures#184]
### Describe the issue

When starting up the game with Valhelsia Structures, it doesn't start up and just crashes. I believe this is related to this issue: https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/181

That issue says Forge 40.2.6 broke something in the mod but I thought I would report anyways just in case it may be related to something else.

In case anyone is concerned, the ATLauncher Console log I provided does say it failed to scan files for Fractureiser but I just used the Overwolf Scanner as well as manually checked myself and I could not detect any Stage 0 or Stage 2 files on my system.

Removing Valhelsia Structures fixes it and game starts fine, exploring a world results in no crashes. I can provide an exported ATLauncher instance but I cannot directly upload it here because it's over 25MB, so here is a modlist:
[MODLIST.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/12369198/MODLIST.txt)

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.3
- Valhelsia Structures: 1.0.2
- Valhelsia Core: 0.5.0

### Log

```shell
https://gist.github.com/SeducedEnvelope/21bddf8aeea760e93ffcbd2c579cc3dd#file-valhelsia_structures_crash-txt
```

**Comment by Vaelzan** [comment]
You need to either update Forge or downgrade Valhelsia Structures to 1.0.1.

Version 1.0.1 is compatible with Forge 43.2.5 and earlier.
Version 1.0.2 is compatible with Forge 43.2.6 and later.
