### ISSUE TITLE
[Bug, 1.18.2]: placeDousedTorch mixin error

### ISSUE THREAD

**Issue by Catomax262** [stal111/Valhelsia-Structures#186]
### Describe the issue

It just crashes on start

### Minecraft Version

1.18.2

### Mods Version

- Forge: 40.2.5
- Valhelsia Structures: 0.1.1
- Valhelsia Core: 0.4.0

### Log

```shell
https://mclo.gs/CNWfOZt
```

**Comment by Vaelzan** [comment]
You updated Valhelsia Structures to the version that is only compatible with newer versions of Forge.

Please stop opening new issues for the same thing.

If you're using Valhelsia Structures 0.1.1, use Forge 40.2.6 or later.
If you're using Valhelsia Structures 0.1.0, use Forge 40.2.5 or earlier.

In neither of your issues were you doing that.
