### ISSUE TITLE
[Bug]: Crash on boot (Mixin apply failed valhelsia_structures.mixins.json:BucketItemMixin)

### ISSUE THREAD

**Issue by BelgianDev** [stal111/Valhelsia-Structures#187]
### Describe the issue

When the game launches it crashes because BucketItemMixin seems to try injecting code into a method that does not exist in the BucketItem class.

### Minecraft Version

1.18.2

### Mods Version

- Forge: 40.2.4
- Valhelsia Structures: 1.18.2-0.1.1
- Valhelsia Core: 1.18.2-0.4.0

### Log

```shell
https://gist.github.com/Raft08/5c69a4be58f43705c604cbd965b795ca
```

**Comment by Vaelzan** [comment]
You're using an old version of Forge. More recent versions of Forge made a breaking change to buckets. Either update Forge or use the previous version of Valhelsia Structures.

**Comment by BelgianDev** [comment]
Thanks for the fast reply!
