### ISSUE TITLE
[Bug]: Cut Oak Post bug that crashes?

### ISSUE THREAD

**Issue by DragonGirl7567** [stal111/Valhelsia-Structures#188]
### Describe the issue

I came upon a house (a Valhesia structure) that was over lava. parts were on fire and suddenly it crashed. not entirely sure what is happening, but when i keep going in, it keeps crashing.

### Minecraft Version

1.20.1

### Mods Version

- Forge:        47.2.1
- Valhelsia Structures:      valhelsia_structures-forge-1.20.1-1.1.0.jar
- Valhelsia Core:        valhelsia_core-forge-1.20.1-1.1.1.jar

### Log

```shell
The game crashed whilst exception ticking world
Error: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.core.Direction$Axis, values=[x, y, z]} as it does not exist in Block{valhelsia_structures:cut_oak_post}

https://gist.github.com/DragonGirl7567/9bc784a9d5369ab9f9e62c8ac03041c5#file-gistfile1-txt

(sorry if I didn't understand this part)
```

**Comment by DragonGirl7567** [comment]
Note: I think now that it is the breaking animation (or whatever it is called) that is not working right on the oak posts (cut and whole)
Only Oak posts with the bark on them, stripped ones are fine (and so are the other variants of woods, stripped and not stripped of bark)

**Comment by DragonGirl7567** [comment]
think also stripped-cut oak that is put together (like 2 cut post in one block section (if I am explaining right))

**Comment by stal111** [comment]
That crash is caused by the Tree Harvester mod, you'll need to remove it. It would be awesome if you could open an issue on their github though.

**Comment by messaiify** [comment]
I am still having this issue (won't even load up the game) with allthemods 9 pack and the tree harvester mod is not in the pack.
