### ISSUE TITLE
[Bug]: Crash If FTB Chunk is Install 

### ISSUE THREAD

**Issue by xbon60** [stal111/Valhelsia-Structures#200]
### Describe the issue

the game crash if i have FTB Chunk Install with Valhelsia Structures, i create issue on the FTB Chunk Github but I was told that the problem came from Valhelsia Structures, and in the issue on Minecraft Version a can't select 1.20.1 

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 1.20.1-47.2.20
- Valhelsia Structures: 1.20.1-1.1.1
- Valhelsia Core: 1.20.1-1.1.1.
- ftb-chunk-forge:2001.2.7

### Log

```shell
https://pste.ch/opamoselox.pl
```

**Comment by Vaelzan** [comment]
Please update to the newest version of the mods before reporting a bug. That one was already fixed in Valhelsia Structures 1.1.2 and Core 1.1.2.
