### ISSUE TITLE
[Bug]:  Valhelisa latest Forge version 1.20.1 crash with the latest Optifine 1.20.1 version.

### ISSUE THREAD

**Issue by Waslikethem** [stal111/Valhelsia-Structures#201]
### Describe the issue

Valhelisa latest Forge version 1.20.1 crash with the latest Optifine 1.20.1 version.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge:
- Valhelsia Structures:
- Valhelsia Core:

### Log

```shell
Valhelisa latest Forge version 1.20.1 crash with the latest Optifine 1.20.1 version.
```

**Comment by urmet** [comment]
not a bug.

optifine isn't supported. even the issue template states that, so you can't miss it while submitting

**Comment by Vaelzan** [comment]
Also a duplicate issue report.
