### ISSUE TITLE
Buildings cut into terrain

### ISSUE THREAD

**Issue by WenXin20** [stal111/Valhelsia-Structures#22]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Valhelsia Structures v15.0.3a`

Buildings can sometimes cut into the terrain. Is it possible to avoid this by making it look more natural, similar to how villages do it?
![2020-07-24_19 25 43](https://user-images.githubusercontent.com/12000593/88444689-e6b34500-cde3-11ea-8a20-829079b71185.png)

**Comment by Khytwel** [comment]
This should be fixed for the next update (not 100% sure).

**Comment by Khytwel** [comment]
Normaly, it's fixed in the last update for version 1.16.1. This will also be ported for old versions.
