### ISSUE TITLE
New Structure Ideas

### ISSUE THREAD

**Issue by AbsorbingSafe11** [stal111/Valhelsia-Structures#25]
While not the most original ideas, can the classic structures from older versions of modded minecraft be added with your team's style?
 For examples
1) castle in the sky
2) pirate boat
3) pyramid maze
4) light house
5) abandoned mage tower
6) temple of the nether

**Comment by AbsorbingSafe11** [comment]
New to using git hub, I was trying to set as enhancement, but didn't know how.

**Comment by pelicanombre** [comment]
How about movies themes structures?
Maybe literature books stories, old arcade themes. Even music genres, bands themes, or paintings.

Or a world concept structure based in for example: bananas, beans, cook utensils.
Everything could be around and related to that object/s (banana dog, bean canoe, fork horse, sponge tree, etc, etc, etc.

Also an anatomy world structure (any organism, not only a human).

Just to be clear, I am not a programmer or app developer and just start using Github like 15 minutes ago.
I hope to learn something about coding, but right now I was searching and I found this and I thought to give it a try and share a few ideas.

**Comment by Khytwel** [comment]
Thank you for your suggestions. We will write them down and see if it is worth implementing them or not. Please note that Valhelsia Structures will soon have its own storie, moreover, the next updates will be on themes such as the Jungle for example.
