### ISSUE TITLE
[Suggestion] Config to not add Wood Post recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [stal111/Valhelsia-Structures#26]
Hi!

I would like to suggest a config for disabling recipes for wood posts, or even better, datapack support. The axe + log recipe is conflicting with another recipe, and I'd like to change the Wooden Post recipes to fix it.

Thanks for a great mod :)

**Comment by Vaelzan** [comment]
We should be able to add it in as a config option fairly quickly, with future plans for data pack support as a more long term rewrite.

**Comment by NielsPilgaard** [comment]
Cool, thanks!

**Comment by Khytwel** [comment]
Added in the latest version (16.0.3 for 1.16.3).

**Comment by NielsPilgaard** [comment]
Awesome, thanks.
