### ISSUE TITLE
1.16.3 BYG generator no structures

### ISSUE THREAD

**Issue by ghost** [stal111/Valhelsia-Structures#33]
I am assuming its down to the BYG world gen but had the Structures mod installed for a while and despite resetting my world and exploring I have yet to see a single structure..... I could of been just unlucky but equally you could have an issue with the biomes in BYG
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

**Comment by Khytwel** [comment]
If there is a compatibility problem, I invite you to report it directly to them.
