### ISSUE TITLE
[Bug] My client won't stop trying to connect to my Minecraft Realm with this mod in my mods folder

### ISSUE THREAD

**Issue by iMoobert** [stal111/Valhelsia-Structures#35]
This mod loads fine in single player, but when I have this mod in my mods folder and I try connecting to my Minecraft Realms, the "Connecting to the realm..." with the little animation below won't stop. My gf has told me that I join and disconnect immediately after, but my screen never shows this. There is no error message or code, just nothing happens.

The game doesn't crash, I just have to press 'back' to exit the "connecting to the realm" page

Java version: 1.16.3
Forge version: 34.1.0

**Comment by ScottKillen** [comment]
Please attach your forge log (.minecraft/logs/latest.log) by dragging it onto a new comment.

**Comment by iMoobert** [comment]
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/5337777/latest.log)

I hope that's linked properly, it's 9466 lines so I don't think it's a good idea to copy/paste it lmao

**Comment by ScottKillen** [comment]
Agreed. Dragging and dropping it was the Right Thing™.

The log that you attached does not show that Vaelehlsia Structures is present...and since it is not a client only mod like Xero's minimap or Optifine, which are shown, Realms would not be avialable.

**Comment by iMoobert** [comment]
Ohh, I see.
I assumed it just wouldn't affect my realm since Minecraft Realms can't be modded in the first place. Thanks for all the info, I guess I'll just take it out of my mods folder whenever I want to go onto my realm.
