### ISSUE TITLE
(1.16.3) Several ConfiguredStructures aren't registered.

### ISSUE THREAD

**Issue by Mysteriaa** [stal111/Valhelsia-Structures#36]
Found in a log when loading a world with Biomes O'Plenty installed:

  Unregistered ConfiguredStructures
valhelsia_structures:forges
valhelsia_structures:castles
valhelsia_structures:castle_ruins
valhelsia_structures:player_houses
valhelsia_structures:desert_houses
valhelsia_structures:tower_ruins
valhelsia_structures:dungeon1/entrances

**Comment by Khytwel** [comment]
It wasn't a problem on our side, it was a problem on Biomes O' Plenty side. Problem fixed in their latest version.
