### ISSUE TITLE
Funky spawning for some of the structures, spawn uprooted

### ISSUE THREAD

**Issue by BugmanBugman** [stal111/Valhelsia-Structures#37]
![2020-10-14_16 16 01](https://user-images.githubusercontent.com/40730042/96047617-05513700-0e3b-11eb-8609-c3035c7827c9.png)
![2020-10-14_16 16 08](https://user-images.githubusercontent.com/40730042/96047620-06826400-0e3b-11eb-9938-acc47474b19f.png)
![2020-10-14_16 16 04](https://user-images.githubusercontent.com/40730042/96047623-071afa80-0e3b-11eb-990b-fc01bf8970bf.png)

**Comment by Khytwel** [comment]
It's not a bug, it can happen at certain times but it's completely normal. If you want this to happen less, in the config file you can change the "flatness_delta" but this can make the structures rarer.
