### ISSUE TITLE
Structures does not generate, console full of errors

### ISSUE THREAD

**Issue by NicolaSpadari** [stal111/Valhelsia-Structures#40]
Minecraft version: 1.16.3
Forge version: 34.1.23

Problem: structures do not generate, no matter what settings I try.
Tried both with and without biome mods (eg. Biomes O Plenty) and other structures mod.
I tested the generation in a new world for like 2 minutes, and my log file was around 60mb size. When I try the `/locate` command, the game freezed and i had to force stop the process.

Log of the problem: [here](https://pastebin.com/SK584sRy) (just posted a part, it's all the same, just in different chunks)

**Comment by EnterFor** [comment]
Same question.. It's been bothering me

**Comment by Khytwel** [comment]
Considering the date, I close this issue, feel free to reopen an issue if it still doesn't work on the latest version of Valhelsia Structures (1.16.5-0.1.0).
