### ISSUE TITLE
Mod started crashing on MC 1.16.3

### ISSUE THREAD

**Issue by LvSweet20** [stal111/Valhelsia-Structures#42]
Hello, so, I have been using this mod with some other mods to play Minecraft 1.16.3 on a server. I have been using same mods without any problem for a week or more, but exactly today Valhelsia Structures just fails to load correctly. I haven't even changed a thing, so that might not be an another mod issue. And I'm also using latest forge version, and even tried to launch Minecraft with different Forge versions. Here's the log: 
[crash-2020-10-25_18.34.05-fml.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/5435362/crash-2020-10-25_18.34.05-fml.txt)
(I Hope, I correctly inserted a log file)

**Comment by Vaelzan** [comment]
Hello.

That crash log indicates that there's an issue with a config file. You could try deleting the Valhelsia Structures configs and allow them to regenerate.
