### ISSUE TITLE
lighting crash

### ISSUE THREAD

**Issue by croftyraider** [stal111/Valhelsia-Structures#44]
I was boating around in my world and noticed that the minimap stopped updating and indeed I could see the edge of the world. Looked at the log, and all the worker threads for lighting had crashed because of this (just one example of many):

`[01Dec2020 17:18:10.238] [Worker-Main-8/WARN] [net.minecraft.world.gen.WorldGenRegion/]: Tried to access a block entity before it was created. BlockPos{x=-296, y=54, z=1405}
`

I did some googling and found something similar with your mod and so instead of just outright disabling the mod what I did was edit the world server config and on a hunch I disabled the generation of the "small dungeons". I reloaded the world and the crashing stopped.

I AM using Biomes O' Plenty among other mods and the area I was boating around in was swampy and the only structure you have currently that generates in the swamp is the small dungeon (which is why I guessed it might be the culprit).

Hopefully that will help track down the issue?

**Comment by Khytwel** [comment]
Considering the date, I close this issue, I invite you to test the latest version (1.16.5-0.1.0). Feel free to reopen an issue if it still doesn't work on the latest version.
