### ISSUE TITLE
Crafting Conflict With No Tree Punching

### ISSUE THREAD

**Issue by BigIronManod** [stal111/Valhelsia-Structures#54]
Running minecraft 1.16.3 with this mod and no tree punching installed and for some reason when i try to use the saw with log in NTP to make the 8 sticks it only lets me make a log beam. The crafting recipe for that item in JEI shows that it needs any type of axe to craft.

**Comment by Vaelzan** [comment]
It's completely normal for different mods to have the same recipe inputs. This isn't a bug, it's extremely common, and it is normal to have to modify recipes when using different mods together (which is one of the things that mod pack creators do).

You need to either use a mod like Polymorph to resolve it, or change the recipe via a data pack, CraftTweaker, or KubeJS.
