### ISSUE TITLE
Issue with config

### ISSUE THREAD

**Issue by faeldray** [stal111/Valhelsia-Structures#58]
Valhesia Structures: 16.0.5
Forge: 36.0.40
Other mods: none

Either the config isn't working like it should or I'm really misunderstanding how it works.

Basically I can get structures to spawn with the default config but they're often thousands of blocks away from spawn (according to `/locate`) and I would like them to be a lot closer/more numerous. So I've been trying different numbers in the config and adding more biomes but nothing seems to work. In [this extreme example](https://pastebin.com/sLavJTHQ), there should be structures everywhere yet none appear when I create a new world and `/locate` can't find any of them now. This is with the config in the \defaultconfigs folder by the way.

**Comment by aditya-jagdev** [comment]
Facing the same issues. My setup:

Mod Ver: 16.0.5
MC Ver: 1.16.4
Forge Ver: 35.1.28

Hope there's some fix soon.

**Comment by ShootToKillSTK** [comment]
I believe you have to put this in default configs folder for it to work, they generate it in normal config even though it doesn't work there

- Though I don't know if I recommend because I had many crashes for no reason trying to edit things.

**Comment by faeldray** [comment]
@ShootToKillSTK I changed both the file in the defaultconfig folder and the one in the config folder to be the same when I did my testing.

**Comment by Khytwel** [comment]
Hi! I invite you to try our latest version (1.16.5-0.1.0), the config file has been improved, this problem should be fixed. 
Considering the date, I close this issue, feel free to reopen an issue if it still doesn't work on the latest version.
