### ISSUE TITLE
structures are generated far away

### ISSUE THREAD

**Issue by Angelous-UI** [stal111/Valhelsia-Structures#59]
when I entered a world I was looking for a mod structure but no matter how many blocks I kept walking I couldn't find any until I used the /locate command and it showed me that the closest structure was 12,516 blocks away and the same with other worlds, not only 12,516 there were also 7,516 or 8,000 and so on, why?

**Comment by DereC4** [comment]
^^^

**Comment by DereC4** [comment]
This is occurring on my worlds too

**Comment by Khytwel** [comment]
There distance can be high depending on the mods that change the generation you added. But this should be fixed in the next update which should arrive soon.

**Comment by Khytwel** [comment]
I invite you to try our latest version (1.16.5-0.1.0), the config file has been improved. Some structures are still a bit rare with Biomes O' Plenty but we are working on it.
Considering the date, I close this issue, feel free to reopen an issue if it still doesn't work on the latest version.
