### ISSUE TITLE
[1.16.5-0.1.0] Structures generation with Biomes O' Plenty

### ISSUE THREAD

**Issue by sfiomn** [stal111/Valhelsia-Structures#60]
Hello,

First of all, the structures in your mod are incredible !

I try to understand the way structure are generated in the biomes (using Biomes o' plenty)
I used this setup:

> [structures.castle]
> 		#Generate Castles?
> 		generate = true
> 		#Castle Spawn Chance [default: 0.5]
> 		#Range: 0.0 ~ 1.0
> 		spawn_chance = 1.0
> 		#Castle Distance (in chunks) [default: 40]
> 		#Range: 1 ~ 500
> 		distance = 40
> 		#Castle Minimum Separation (in chunks) [default: 8]
> 		#Range: 1 ~ 500
> 		separation = 8
> 		#Biome Types the Castle can generate in
> 		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
> 		#Biomes the Castle can NOT generate in
> 		biome_blacklist = []

My understanding is each biomes with category Plains, Forest or Taiga will spawn a castle because of the spawn_chance = 1.
For what I see, it isn't the case at all (closest Castle 7000 blocks away).

The delta of the flatness is 4

Plains like the golden prairy doesn't have a castle by example.

What am I missing to try to increase the spawn rate of Valhesia structures through the world ?

Thanks for your time

**Comment by Khytwel** [comment]
Hi, thanks! Regarding your problem, I invite you to try our latest version (1.16.5-0.1.0), the config file has been improved. Some structures are still a bit rare with Biomes O' Plenty but we are working on it. If you want to make the castle a little less rare you can lower the "spacing" and increase the "spawn_chance".
