### ISSUE TITLE
[1.16.5-0.1.0] Crash w/ Bgcore

### ISSUE THREAD

**Issue by WenXin20** [stal111/Valhelsia-Structures#61]
`Minecraft v1.16.5`
`Forge v36.1.9`
`Vahelsia Structures v16.0.5`
[`Bgcore v3.2`](https://www.curseforge.com/minecraft/mc-mods/bgcore)
[`CCB v5.1`](https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport)

My server crashed while I was exploring. The crash occurred with Bgcore, which is the required mod for Caves and Cliffs Backport and crashed due to the biome height.
[Crash Report](https://gist.github.com/WenXin20/878ba27d6613e1ba7ce8ff3516cb8bd3#file-bgcore_crash-txt-L34)

**Comment by stal111** [comment]
The issue is most likely caused on Bgcore's side so it would be good if you could also open an issue on their tracker.

**Comment by WenXin20** [comment]
Alright, thanks. I let the dev know in his discord and is looking into it.

**Comment by stal111** [comment]
Just tested with the newest version of CaveBiomeAPI and it no longer crashes.
