### ISSUE TITLE
Newest Release Crashing Server

### ISSUE THREAD

**Issue by SuburbanLani** [stal111/Valhelsia-Structures#66]
Not particularly sure what the issue is but I have a server running the latest beta version (valhelsia_structures-16.0.5.jar) of the Valhelsia structures mod and my server ran fine. Then I updated to the newest release (valhelsia_structures-1.16.5-0.1.0.jar) and now my server no longer starts and I get a crash error in my server's console.

Not sure if the Valhelsia core is the issue or not because my server runs fine without it and using the beta version of the Valhelsia Structures.

**Comment by Sparktion** [comment]
Getting the same issue

**Comment by rleong** [comment]
I'm also getting the same issue.
`14.05 22:41:42 [Server] INFO Mod File: valhelsia_structures-1.16.5-0.1.0.jar
14.05 22:41:42 [Server] INFO Failure message: Valhelsia Structures has class loading errors
14.05 22:41:42 [Server] INFO java.lang.ExceptionInInitializerError: null
14.05 22:41:42 [Server] INFO Mod Version: 1.16.5-0.1.0
14.05 22:41:42 [Server] INFO Mod Issue URL: https://github.com/stal111/Valhelsia-Structures/issues
14.05 22:41:42 [Server] INFO Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/LivingRenderer for invalid dist DEDICATED_SERVER
14.05 22:41:42 [Server] INFO Stacktrace:
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.1] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
14.05 22:41:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.valhelsia.valhelsia_core.registry.RegistryManager$Builder.build(RegistryManager.java:103) ~[valhelsia_core:16.0.7] {re:classloading}
14.05 22:41:42 [Server] INFO at com.stal111.valhelsia_structures.ValhelsiaStructures.<clinit>(ValhelsiaStructures.java:54) ~[valhelsia_structures:1.16.5-0.1.0] {re:classloading}
14.05 22:41:42 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:36.1] {re:classloading}
14.05 22:41:42 [Server] INFO at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source) ~[?:?] {}
14.05 22:41:42 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:36.1] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
14.05 22:41:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
14.05 22:41:42 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
14.05 22:41:42 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
14.05 22:41:42 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}`

**Comment by Khytwel** [comment]
I merge this issue with this issue: https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/69. For next time, please provide a crash report with GitHub Gist (https://gist.github.com/).
