### ISSUE TITLE
Add support for realistic torches/options to configure the new doused torch

### ISSUE THREAD

**Issue by Yzelast** [stal111/Valhelsia-Structures#67]
Hi guys, just came to ask some questions about the new doused torch mechanic. There are plans to make them craftable like a normal torch? if not, maybe an option to just use the default torches...or maybe an option to configure which block to generate as torch inside the dungeons, maybe add support to realistic torches, so we don't have to have 2 different types of torches...

**Comment by Khytwel** [comment]
Hi, this is not something that is feasible on our side sorry. There will always be duplicate blocks depending on the mods that are used with Valhelsia Structures.
