### ISSUE TITLE
[1.16.5-0.1.0] Jar reacting badly to shaders

### ISSUE THREAD

**Issue by Krampus69** [stal111/Valhelsia-Structures#68]
Hello,
New jar blocks react badly to some shaders. I use BSL, also tried it with BeyondBelief and the texture error was still there.
![2021-05-15_06 18 42](https://user-images.githubusercontent.com/81943963/118347733-c2c51980-b545-11eb-8b41-bbd5b1e456b7.png)

This issue doesn't occur with Chocapic13 but honestly I don't have the detail on how chocapic handles these faces, it usually still works with it. I'll say it's probably a normal issue, probably linked to the mesh itself.

**Comment by Krampus69** [comment]
![2021-05-15_06 25 05](https://user-images.githubusercontent.com/81943963/118347830-63b3d480-b546-11eb-8966-3fcd36694f67.png)

![2021-05-17_13 04 39](https://user-images.githubusercontent.com/81943963/118478732-81cd3080-b710-11eb-9a8f-67bf93527c21.png)


Also no structure void on the structures

**Comment by Krampus69** [comment]
Hello hello,
Just so you know and for everyone else who has the same issue : The dark faces on the jars can be fixed in the shaders parameters. They usually have a block.properties (mine is BSL shaders for example) in their .rar and you can fix the glitch by adding the object id to the "no AO" line.
This is an ambient occlusion bug, managed to correct this problem and it now works perfectly without any visual artifacts. You can close this thread: )

**Comment by Khytwel** [comment]
Thanks for your feedback, as for the structures that cut the trees, normally this does not happen anymore on the latest versions. For the structures we can't do anything, we could add a check but it could take a lot of performance.
