### ISSUE TITLE
[1.16.5-0.1.0] Server Crash

### ISSUE THREAD

**Issue by WenXin20** [stal111/Valhelsia-Structures#69]
`Forge v36.1.16`
`Minecraft v1.16.5`
`Valhelsia Core v16.0.7`
`Valhelsia Structures v0.1.0`
`Forbidden Arcanus v16.2.0-beta-3`

When loaded on a server, it crashes.
[Crash Report](https://gist.github.com/WenXin20/cafde7dc64336469fa6ac875ccb4b6df)

**Comment by Darkmega18** [comment]
got this. minus forbidden arcanus. here.
[crash-2021-05-15_05.32.31-fml.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6485176/crash-2021-05-15_05.32.31-fml.txt)

**Comment by didis54** [comment]
Same here
[crash-2021-05-15_11.22.04-fml.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6485521/crash-2021-05-15_11.22.04-fml.txt)

**Comment by Khytwel** [comment]
A [new version](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core/files/3310381) of our API has been released, the problem should be fixed.

Make sure to have the latest version of Valhelsia Core (16.0.8).
