### ISSUE TITLE
Structures not spawning with william wythers datapack

### ISSUE THREAD

**Issue by Tchozerino** [stal111/Valhelsia-Structures#71]
hi i'm having a problem with the datapack William Wythers' Overhauled Overworld 1.16.5
when I generate my world with it the structures of the mod are not generated, I would like to know what I can do from now thanks

version 1.16.5 0.1.1

valhelsia core16.0.8

**Comment by Khytwel** [comment]
Have you tried the /locate command?

**Comment by Tchozerino** [comment]
yes

**Comment by Tchozerino** [comment]
I tried all the commands / locate, as I am in large biomes I teleported in different biomes, and used / locate, and nothing

**Comment by Tchozerino** [comment]
I figured out how to fix the problem between worldgen datapacks and structure mods.
but i need the valhelsia ID name 

is like ''valhelsia_structure:castle_ruin''
or '' valhelsiastructure:castle_ruin''
