### ISSUE TITLE
Please help me understand an issue

### ISSUE THREAD

**Issue by Coltenlee** [stal111/Valhelsia-Structures#74]
Is there any possibility that this will cause the patrol and wandering Trader not spawn?
Since I installed it, I haven’t seen them spawn for a week.
I installed multiple mods at once including this, so now I am filtering them.

**Comment by Vaelzan** [comment]
I can confirm that Valhelsia Structures does not prevent either from spawning. I have the latest version running on my server and have had both appear as normal.

I might be able to help you rule out some other mods too by saying that both pillager patrols and wandering traders appear in the modpack Valhelsia 3, so it won't be any of the mods that we include in that pack causing it (assuming some of the mods you added overlap the ones in the pack).

**Comment by Coltenlee** [comment]
Thank you for help!
 I installed :
Savage and Ravage
The Endergetic Expansion
Better Strongholds
and your mod.
But I think S&R is most likely.
