### ISSUE TITLE
Big Jars void any block that is higher than jar.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [stal111/Valhelsia-Structures#78]
_**Versions:**_
**Minecraft:** 1.16.5
**Forge:** 36.1.31
**Valhelsia Core:** 16.0.9
**Valhelsia Structures:** 0.1.2 (tested with 0.1.1 too)

If you place Big Glazed Jar under any block, block which is higher than this jar will just disappear. Anything will disappear. Even chests with items (but items sometimes will be just dropped on the ground)

**Steps to reproduce:**
1. Find any pickaxe with Silk Touch and find any Big Glazed Jar in your world and get it into inventory.
2. Then place this jar under any block you want.
3. Watch the block disappear and feel sad that you've just broke a block no matter what it is - bedrock or ME Controller with your storage disks or just dirt.

Screenshots/Videos:
[Short video](https://www.reddit.com/link/nz4xh0/video/7owejodrm2571/player)

Log? [Here it is.](https://gist.github.com/DenisMasterHerobrine/14ce6687bbbe6e9ba0cb8a72be507015)

**Comment by Vaelzan** [comment]
Thanks for the report. I think I've got a pretty good idea of a fix already, so it shouldn't be too hard to resolve for 0.1.3 in the future.

**Comment by Vaelzan** [comment]
Fixed in the 0.1.3 release on CurseForge.
