### ISSUE TITLE
Can't find any structure :(

### ISSUE THREAD

**Issue by HQuality17** [stal111/Valhelsia-Structures#79]
Hey, I've been walking a lot, but I can't find any structure, I got the Valhelsia 0.1.2 and Valhelsia Core. I tried with other Mod versions but it doesnt work, what's going on? :( (I created some new worlds btw)

**Comment by HQuality17** [comment]
In the other hand, im using Forge 36.1.4
;D

**Comment by Vaelzan** [comment]
Please try using the `/locate` command (requires cheats enabled or to be an op on a server) to see if they're just rare, or not spawning at all, for example, `/locate valhelsia_structures:castle`.

You can adjust the rarity in the config file, and they will need to be made more common when used alongside mods like Biomes o Plenty and some other biome or world generation mods that have a different balance of biomes.
