### ISSUE TITLE
worldgen crash in  0.1.2

### ISSUE THREAD

**Issue by CKY-** [stal111/Valhelsia-Structures#84]
Minecraft version: 1.16.5
Forge version: 36.1.25
Valhelsia version: 0.1.2

In a large pack with twilight forest. entering the map throw's an error.

Valhelsia_structures.block.DungeonDoorBlock

https://gist.github.com/CKY-/d17b7b486b903428e47a6cd26b2ff6f8

**Comment by Dubslash** [comment]
Minecraft Version: 1.16.5
Forge Version: 36.1.25
Valhelsia Version: 3.3.3
V. Structures Version: 0.1.2

Same here.

Tested in Singleplayer.
With Valhelsia Structures = Game Crash
Without Valhelsia Structures = No Crash
With Valhelsia Structures and Twilight Forest worldreset = Game Crash

[crash-log_debug.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6682906/crash-log_debug.txt)

**Comment by Vaelzan** [comment]
This should be fixed in 0.1.3, released yesterday.
