### ISSUE TITLE
Ticking Entity Spawner Dungeon Drowned

### ISSUE THREAD

**Issue by Jollyolsport** [stal111/Valhelsia-Structures#85]
Whenever I come across a drowned inside a spawner dungeon and it agros on me the game crashes giving me a ticking entity report. 
valhelsia version: 1.16.5-0.1.2
forge version: 36.1.24
minecraft version: 1.16.5
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6706168/latest.log)

**Comment by stal111** [comment]
I don't think that this issue is caused by Valhelsia Structures, at least it isn't mentioned in the crash log. Feel free to reopen if you still have the same problem in the newest version (but please upload the full log if that's the case, otherwise we won't be able to help).

**Comment by Jollyolsport** [comment]
Sorry shouldve closed it, but the issue was stemming from a different mod called "improved mobs".
