### ISSUE TITLE
Structures spawn in Middle-Earth

### ISSUE THREAD

**Issue by WordStormRose** [stal111/Valhelsia-Structures#86]
Hello,

I am using this mod in tandem with Lord of the Rings: Renewed, and structures from here keep spawning in Middle-Earth even when I try to add the LotR biomes to the global biome blacklist in the config. I've edited the config multiple times but every single time after that when I look to check it's gone back to default. 
Could you make it so that either these structures only spawn in the overworld or so that the biome blacklist doesn't revert changes when they're made?

Thanks!

**Comment by Vaelzan** [comment]
Are you changing the blacklist while the game is open or closed? It certainly isn't normal for the blacklist to revert unless there's an issue in the config file (it will revert to default if the config is invalid) or if the game is open while editing it.

There's also a feature coming in the next update that will let you add wildcards to blacklists to block entire dimensions. Eg. "twilightforest*" would block all the Twilight Forest biomes.

**Comment by WordStormRose** [comment]
I have been doing it while the game was open so I could use the /locatebiome command to get the biome ids, but last time I copied the list to a different spot so I wouldn't have to manually type everything again so I'll try with the game closed.

**Comment by Vaelzan** [comment]
I just edited my comment above, I accidentally sent it while I was writing (slipped on my phone).

**Comment by WordStormRose** [comment]
Thank you. My other changes (adding more biome types to a few different spawning being allowed areas) stayed consistently, it was just the lotr biome additions to the blacklist that reverted.

**Comment by Vaelzan** [comment]
The biome wildcards have now been implemented in the 0.1.3 release.
