### ISSUE TITLE
Upgraded tools do not mine valhesia structures blocks any faster than default speed

### ISSUE THREAD

**Issue by insectopod** [stal111/Valhelsia-Structures#90]
Noticed specifically with Valhesia Strucutres Dirt, Coarse Dirt, and Grass Blocks, using a diamond shovel.

**Comment by Vaelzan** [comment]
Already fixed in the code for the upcoming release. :) Should be on CurseForge within a few days unless we find anymore bugs during testing.

https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/9360db21dd7e8c68de905a5a3eaabc6f5f03c194

**Comment by stal111** [comment]
Fixed in release 0.1.4 on CurseForge.
