### ISSUE TITLE
Relightable Doused Torches

### ISSUE THREAD

**Issue by Golfavel** [stal111/Valhelsia-Structures#92]
Currently once a torch is doused it cannot be reverted to a normal torch; this should be changed so that either crafting them with a Flint & Steel will produce a relit/default torch, or by physically lighting them in-world with a Flint & Steel (and similar items) will relight them.

**Comment by Vaelzan** [comment]
Doused Torches can already be lit with Flint & Steel by right-clicking on them (as long as they aren't still waterlogged).

If this isn't working for you then I would need more information from you, such as a full mod list (or if you're using any other software, such as Mohist), to see if there may be potential inter-mod conflicts.

**Comment by Khytwel** [comment]
No additional information so I close the issue.
