### ISSUE TITLE
Doused Torch seemingly causing crash with bamboo torch from Bamboo Blocks

### ISSUE THREAD

**Issue by Smokedeuch** [stal111/Valhelsia-Structures#93]
[crash-2021-08-08_15.34.21-client.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6951422/crash-2021-08-08_15.34.21-client.txt)

**Comment by Rimevel** [comment]
Can confirm, this just happened for me as well right now. Seems to be a mixin issue of some kind.
Also I can no longer enter my world without instantly crashing again :(

**Comment by stal111** [comment]
This has been fixed in version 0.1.5.
