### ISSUE TITLE
broken world gen with spawner dungeons

### ISSUE THREAD

**Issue by Wedge1453** [stal111/Valhelsia-Structures#94]
the server console was spamming "Error adding element: Base value out of range: 250 [-10-128]"
so we added Blame and got this: 
http://cdn.deswashere.tk/latest.log

**Comment by botmaker69** [comment]
Im the one with the issue, and im crashing on connect to my server, wedge and others can connect fine for some odd reason, its just me that crashes

**Comment by stal111** [comment]
This was fixed in version 0.1.5.
