### ISSUE TITLE
Valhelsia Structures Compatibility With Mo's Structures

### ISSUE THREAD

**Issue by Tinn04** [stal111/Valhelsia-Structures#95]
![2021-08-16_17 25 46](https://user-images.githubusercontent.com/69121624/129645315-03b76666-3b4c-4a9d-b38c-b3b3d4c647f8.png)
I was searching for a player house and used the /locate command. When I did I was surprised to find the structure inside of another structure. Is this a bug or a compatibility issue between the two mods?

**Comment by stal111** [comment]
Just a bug that can happen rarely. To fix that we would need to check for other structures before generating ours, however this could impact performace.
