### ISSUE TITLE
patch 0.1.5 failed world loading

### ISSUE THREAD

**Issue by Petrisis** [stal111/Valhelsia-Structures#97]
This is Minecraft 1.16.5, Forge 36.2.2, ValhelsiaStructures 0.1.5 with ValhelsiaCore 16.0.9.

**The Problem**
loading newly created worlds or already existing worlds never finishes. first the game reads world data and then justs sticks with infinite dirtwall. it never reaches the point of the circle thingy and "joining world" dialogue.
this only happens in my modpack if i update ValhelsiaStructures to the new version 0.1.5. _I updated every other mod separately and tried to load for every patch_

**How to reproduce**
You could load "Crashed on Gyrnolia" CurseForge Pack with the Launcher of your choice or from CF: 
https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia
and then manually update the ValhelsiaStructure Mod. 

Alternatively i provide you a modlist with already updated ValhelsiaStructures-Mod:
[modlist.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7109751/modlist.txt)

It may be an incompatibility problem :/

**Comment by Vaelzan** [comment]
Valhelsia Structures 0.1.5 requires Valhelsia Core 16.0.10, not 16.0.9. Please try updating that too and let us know if the problem persists.

**Comment by Petrisis** [comment]
updating Valhelsia Core fixed the issue.

its rather inconvenient to have a stable version of VStructures require a beta version of VCore. 
additionally VStructures could demand VCore of required version on launch
just suggestions .. thanks for you help!
